services:
  - type: web
    name: excel-summarizer
    env: python
    buildCommand: ""
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: GROQ_API_KEY
        sync: false
